version: '3.5'

networks:
    http_net:
    db_net:
    es_net:

volumes:
    dbdata-test:
    esdata-test:

services:
    elasticsearch-test:
        image: ${ES_IMAGE:-elasticsearch:7.9.1}
        environment:
            - cluster.name=elastic-cluster
            - discovery.type=single-node
            - data
            - bootstrap.memory_lock=true
            - CLI_JAVA_OPTS="-Xms3g -Xmx3g"
        ports:
            - ${ES_HOST_PORT:-9207}:9200
        volumes:
            - esdata-test:/usr/share/elasticsearch/data
        networks:
            - es_net

    db-test:
        image: ${PG_IMAGE:-postgres:11}
        command: postgres -c 'max_connections=400' -c 'shared_buffers=128MB'
        environment:
            'POSTGRES_USER': ${DB_USER:-postgres}
            'POSTGRES_PASSWORD': ${DB_PWD:-postgres}
            'POSTGRES_DB': ${DB_DB:-dotcms}
        volumes:
            - dbdata-test:/var/lib/postgresql/data
        networks:
            - db_net
        ports:
            - '${DB_HOST_PORT:-5437}:5432'
