version: '3.5'

# This works because each elasticsearch instance is publishing its address/port on the 
# External IP - 192.168.86.33

volumes:
  esdata1:
  esdata2:
  esdata3:

services:
  elasticsearch1:
    image:  dotcms/elasticsearch:6.1.3_for_5.2.8
    ports:
      - "9201:9200"
      - "9301:9301"
    environment:
      "DOTCMS_ES_CLUSTER": 'dotcmsProdCluster'
      "ES_NETWORK_PUBLISH_HOST": 192.168.86.33
      "ES_UNICAST_HOST": "elasticsearch1"
      "ES_TRANSPORT_PORT": 9301
      "ES_MIN_MASTER_NODES": 3
      "ES_NODE_MASTER": true
      "ES_NODE_DATA": true
      "ES_JAVA_OPTS": "-Xms2G -Xmx2G"
    volumes:
      - esdata1:/data


  elasticsearch2:
    image:  dotcms/elasticsearch:6.1.3_for_5.2.8
    depends_on:
      - elasticsearch1
    ports:
      - "9302:9302"
    environment:
      "DOTCMS_ES_CLUSTER": 'dotcmsProdCluster'
      "ES_UNICAST_HOST": "192.168.86.33:9301"
      "ES_NETWORK_PUBLISH_HOST": 192.168.86.33
      "ES_TRANSPORT_PORT": 9302
      "ES_MIN_MASTER_NODES": 3
      "ES_NODE_MASTER": true
      "ES_NODE_DATA": true
      "ES_JAVA_OPTS": "-Xms1G -Xmx1G"
    volumes:
      - esdata2:/data

  elasticsearch3:
    image:  dotcms/elasticsearch:6.1.3_for_5.2.8
    depends_on:
      - elasticsearch1
    ports:
      - "9303:9303"
    environment:
      "DOTCMS_ES_CLUSTER": 'dotcmsProdCluster'
      "ES_UNICAST_HOST": "192.168.86.33:9301"
      "ES_NETWORK_PUBLISH_HOST": 192.168.86.33
      "ES_TRANSPORT_PORT": 9303
      "ES_MIN_MASTER_NODES": 3
      "ES_NODE_MASTER": true
      "ES_NODE_DATA": true
      "ES_JAVA_OPTS": "-Xms1G -Xmx1G"
    volumes:
      - esdata3:/data
