version: '3.5'

# For this configuration to work properly, you must have a license file mounted into the dotcms service.
# Without a license file, the external ES service will NOT be recognized and utilized.  All documents will
# indexed on the dotcms node directly and will not be persisted between restarts.

networks:
  es_net:

volumes:
  esdata1:
  esdata2:
  esdata3:

services:
  nginx-ssl-proxy:
    image: danieldent/nginx-ssl-proxy
    restart: always
    environment:
      UPSTREAM: elasticsearch:6.1.3-os:9200
      SERVERNAME: demo.dotcms.com
      EXTRANAMES: test.dotcms.com
      NGINX_CLIENT_MAX_BODY_SIZE: 0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/demo.dotcms.com/etc:/etc/letsencrypt
    networks:
      - es_net

  elasticsearch1:
    image: dotcms/elasticsearch:6.1.3-os
    ports:
      - "9200:9200"
    environment:
      "PROVIDER_ELASTICSEARCH_HEAP_SIZE": '1500m'
      "PROVIDER_ELASTICSEARCH_DNSNAMES": 'elasticsearch1,elasticsearch2,elasticsearch3'
      "PROVIDER_ELASTICSEARCH_SVC_DELAY_MIN": '1'
      "PROVIDER_ELASTICSEARCH_SVC_DELAY_STEP": '1'
      "PROVIDER_ELASTICSEARCH_SVC_DELAY_MAX": '2'

    networks:
      - es_net

  # elasticsearch2:
  #   image: dotcms/elasticsearch:6.1.3-os
  #   depends_on:
  #     - elasticsearch1
  #   environment:
  #     "PROVIDER_ELASTICSEARCH_HEAP_SIZE": '1024m'
  #     "PROVIDER_ELASTICSEARCH_DNSNAMES": 'elasticsearch1,elasticsearch2,elasticsearch3'
  #     "PROVIDER_ELASTICSEARCH_SVC_DELAY_MIN": '3'
  #     "PROVIDER_ELASTICSEARCH_SVC_DELAY_MAX": '30'
  #   volumes:
  #     - esdata2:/data
  #   networks:
  #     - es_net

  # elasticsearch3:
  #   image: dotcms/elasticsearch:6.1.3-os
  #   depends_on:
  #     - elasticsearch1
  #   environment:
  #     "PROVIDER_ELASTICSEARCH_HEAP_SIZE": '1024m'
  #     "PROVIDER_ELASTICSEARCH_DNSNAMES": 'elasticsearch1,elasticsearch2,elasticsearch3'
  #     "PROVIDER_ELASTICSEARCH_SVC_DELAY_MIN": '3'
  #     "PROVIDER_ELASTICSEARCH_SVC_DELAY_MAX": '30'
  #   volumes:
  #     - esdata3:/data
  #   networks:
  #     - es_net
