# action.yml
name: 'Run Integration Tests'
description: 'Run core integration tests'
author: 'victoralfaro-dotcms'
inputs:
  project_root:
    description: 'Project root'
    required: true
    default: ${{ github.WORKSPACE }}
  build_env:
    description: 'Build environment to use'
    required: true
  db_type:
    description: 'Database type'
    required: true
  extra_params:
    description: 'Extra parameters to pass to instruction'
    required: false
  license_key:
    description: 'License key to use'
    required: true
outputs:
  tests-run-exit-code:
    description: 'Test run exit code'
  tests-results-status:
    description: 'Tests results status'
  tests-results-location:
    description: 'Unit tests results location'
  skip-results-report:
    description: 'Flag indicating if results report is skipped'
runs:
  using: 'node16'
  main: 'dist/index.js'
  # using: 'docker'
  # image: 'Dockerfile'
