name: CLI tests
on:
  pull_request:
    paths:
      - 'tools/dotcms-cli/**'
  push:
    branches:
      - 22706-gha-configuration-for-cli-integration-tests
      - master
      - release-*
jobs:
  cli_tests:
    name: CLI tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout core
        uses: actions/checkout@v3
      - name: Run tests
        working-directory: ./tools/dotcms-cli/
        run: |
          pwd
          ls -la
          ./mvn test
#      - name: Run cli tests
#        working-directory: ./tools/dotcms-cli
#        run: |
#          # Acá deberia para levantar las dependecias (DB? Quarkus)
#          ./mvnw test
#      - name: Store results
#        run: |
#          github-de-dani.sh