name: CLI tests
on:
  pull_request:
    paths:
      - 'tools/dotcms-cli/**'
  push:
    branches:
      - master
      - release-*
jobs:
  cli_tests:
    name: CLI tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout core
        uses: actions/checkout@v3
      - name: Prepare license
        env:
          DOTCMS_LICENSE_KEY: ${{ secrets.DOTCMS_LICENSE }}
          DOTCMS_LICENSE_PATH: ${GITHUB_WORKSPACE}/tools/dotcms-cli/license
        run: |
          mkdir -p ${DOTCMS_LICENSE_PATH}
          echo "${DOTCMS_LICENSE_KEY}" > ${DOTCMS_LICENSE_PATH}/license.dat
          export DOTCMS_LICENSE_FILE=${DOTCMS_LICENSE_PATH}/license.dat
      - name: Run cli tests
        working-directory: ./tools/dotcms-cli/
        run: |
          echo $DOTCMS_LICENSE_FILE
          ./mvnw clean verify
#      - name: Github publish tests results
#        uses: ./.github/actions/publish-test-results
#        with:
#          build_id: <branch or commit>
#          test_type: cli # or whatever name you need to
#          pull_request: ${{ github.event.number }} # optional in case the tests are triggered by a PR
#          tests_results_status: PASSED|FAILED # tests results status, optional
#          tests_results_location: # tests results location, optional, most of the time this made up of a bunch of XML files, optional
#          tests_results_report_location: <path to results> # actual reports made from XML files, probably in HTML format
#          cicd_github_token: ${{ secrets.CICD_GITHUB_TOKEN }