name: CLI tests
on:
  pull_request:
    paths:
      - 'tools/dotcms-cli/**'
  push:
    branches:
      - 22706-configure-gha-and-testcontainers-for-cli-test
      - master
      - release-*
jobs:
  cli_tests:
    name: CLI tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout core
        uses: actions/checkout@v3
      - name: Run tests
        working-directory: ./tools/dotcms-cli/
        run: |
          java -version
          pwd
          ./mvnw -version
          ./mvnw test