name: CLI Tests
on:
  pull_request:
    paths:
      - 'tools/dotcms-cli/api-data-model/**'
      - 'tools/dotcms-cli/cli/**'
  push:
    branches:
      - master
      - 'release-*'
jobs:
  cli_test:
    name: CLI Tests
    runs-on: ubuntu-latest
    steps:
      - id: git-checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: run-test-dependencies
        name: Run Test Dependencies
        working-directory: ./cicd/docker
        run: |
          pwd
          docker-compose -f dotcms-compose.yml -f postgres-compose.yml -f open-distro-compose.yml up -d

      # - id: docker-compose-setup
      #   name: Setup Docker Compose
      #   uses: isbang/compose-action@v1.4.1
      #   with:
      #     compose-file: |
      #       open-distro-compose.yml
      #       postgres-compose.yml
      #       dotcms-compose.yml
      #   env: 
      #     DOTCMS_IMAGE: 'dotcms/dotcms:master_a90c97d_SNAPSHOT'
      #     DOTCMS_LICENSE: 'NOTHING BY THE MOMENT'
      #     DB_TYPE: postgres
      #     TEST_TYPE: 'cli'
      #     WAIT_FOR_DEPS: '60'
      #     CUSTOM_STARTER_URL: 'NOTHING BY THE MOMENT'


      # - id: run-dotcms-cli-tests
      #   name: Run DotCMS CLI Tests
      #   uses: ./.github/actions/run-cli-tests
      #   with:
      #     project_root: tools/dotcms-cli
      #     built_image_name: 'dotcms/dotcms:master_a90c97d_SNAPSHOT'
      #     wait_for_deps: 60
      #     db_type: postgres
      #     license_key: 'NOTHING BY THE MOMENT'
      #     custom_starter_url: 'NOTHING BY THE MOMENT'

          # license_key: ${{ secrets.DOTCMS_LICENSE }}
          # custom_starter_url: ${{ secrets.CUSTOM_STARTER_URL }}

      - name: tests
        # working-directory: tools/dotcms-cli
        run: |
          echo 'HELLO DANI'
          pwd
          ls -la



      # - id: run-postman-tests
      #   name: Run Postman Tests
      #   timeout-minutes: 90
      #   uses: ./.github/actions/run-postman-tests
      #   with:
      #     built_image_name: ${{ needs.postman-tests-setup-job.outputs.built_image_name }}
      #     license_key: ${{ secrets.DOTCMS_LICENSE }}
      #     tests: ${{ steps.get-commit-message.outputs.commit_message }}
      #     parallel_collection: ${{ matrix.parallel_collection }}
      #     export_report: ${{ env.PUBLISH_MODE == 'ALL' || env.PUBLISH_MODE == 'RESULTS' }}        


    
      # - name: tests
      #   working-directory: ./tools/dotcms-cli
      #   run: |
      #     echo "tests"
      #     ./gradlew clean test

      




      
  