name: core-tests
on:
  pull_request:
  push:
    branches:
      - master
      - release-*
jobs:
  module-matcher-job:
    name: Module Matcher
    runs-on: ubuntu-latest
    outputs:
      module_found: ${{ steps.module-matcher.outputs.module_found }}
    steps:
      - id: fetch-core
        name: Fetch Core repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: module-matcher
        name: Module Matcher
        uses: ./.github/actions/module-matcher
        with:
          current: core
  build-core-job:
    name: Build Core
    runs-on: ubuntu-latest
    env:
      DEBUG: true
    steps:
      - name: GITHUB CONTEXT
        run: echo "${{ toJson(github) }}"
        if: env.DEBUG == 'true'
      - id: fetch-core
        name: Fetch Core repo
        uses: actions/checkout@v3
      - id: read-cicd-local-env
        name: Read CICD local library
        run: |
          source ${GITHUB_WORKSPACE}/cicd/local-env.sh
        if: success()
      - id: build-core
        name: Build Core
        uses: ./.github/actions/build-core
        with:
          build-tool-env: ${{ env.BUILD_ENV }}
        if: success()
      - id: core-cache-locator
        name: Core Cache Locator
        uses: ./.github/actions/core-cache-locator
        with:
          build-tool-env: ${{ env.BUILD_ENV }}
          core-root: ${{ github.WORKSPACE }}
          cache-build-output: true
        if: success()
      - id: cache-core
        name: Cache Core
        uses: ./.github/actions/cache-core
        with:
          build-tool-env: ${{ env.BUILD_ENV }}
          cache-locations: ${{ steps.core-cache-locator.outputs.cache-locations }}
        if: success()
