name: Core
on:
  pull_request:
  push:
    branches:
      - master
      - release-*
      - issue-23538-vico-tests
jobs:
  repo-metadata-job:
    name: Get Github Metadata
    runs-on: ubuntu-latest
    outputs:
      commit_message: ${{ steps.get-commit-message.outputs.commit_message }}
      module_found: ${{ steps.module-matcher.outputs.module_found }}
    steps:
      - id: fetch-core
        name: Fetch Core repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: read-cicd-local-env
        name: Read CICD local library
        run: source ${GITHUB_WORKSPACE}/cicd/local-env.sh
      - id: module-matcher
        name: Module Matcher
        uses: ./.github/actions/module-matcher
        with:
          build_id: ${{ env.BUILD_ID }}
          current: core
      - id: get-commit-message
        name: Get commit message
        uses: dotcms/get-commit-message@master
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
  build-core-job:
    name: Build Core
    runs-on: ubuntu-latest
    needs: repo-metadata-job
    if: needs.repo-metadata-job.outputs.module_found == 'true'
    env:
      DEBUG: true
    outputs:
      cache_metadata: ${{ steps.cache-core.outputs.cache_metadata }}
    steps:
      - id: fetch-core
        name: Fetch Core repo
        uses: actions/checkout@v3
      - id: read-cicd-local-env
        name: Read CICD local library
        run: source ${GITHUB_WORKSPACE}/cicd/local-env.sh
        if: success()
      - id: build-core
        name: Build Core
        uses: ./.github/actions/build-core
        with:
          build_env: ${{ env.BUILD_ENV }}
        if: success()
      - id: core-cache-locator
        name: Core Cache Locator
        uses: ./.github/actions/core-cache-locator
        with:
          build_env: ${{ env.BUILD_ENV }}
          cache_build_output: false
        if: success()
      - id: cache-core
        name: Cache Core
        uses: ./.github/actions/cache-core
        with:
          build_env: ${{ env.BUILD_ENV }}
          cache_locations: ${{ steps.core-cache-locator.outputs.cache_locations }}
        if: success()
  run-unit-tests-job:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: [repo-metadata-job, build-core-job]
    if: success()
    outputs:
      tests_results_status: ${{ steps.run-unit-tests.outputs.tests_results_status }}
      tests_results_skip_report: ${{ steps.run-unit-tests.outputs.tests_results_skip_report }}
      tests_results_report_url: ${{ steps.github-publish-unit-tests.outputs.tests_report_url }}
      tests_results_log_url: ${{ steps.github-publish-unit-tests.outputs.test_logs_url }}
      testmo_tests_results_report_url: ${{ steps.publish-unit-tests.outputs.tests_report_url }}
    env:
      DEBUG: true
    steps:
      - id: fetch-core
        name: Fetch Core Repo
        uses: actions/checkout@v3
      - id: read-cicd-local-env
        name: Read CICD local library
        run: source ${GITHUB_WORKSPACE}/cicd/local-env.sh
        if: success()
      - id: restore-core
        name: Restore Core Cache
        uses: ./.github/actions/restore-core
        with:
          cache_metadata: ${{ needs.build-core-job.outputs.cache_metadata }}
        if: success()
      - id: run-unit-tests
        name: Run Unit Tests
        uses: ./.github/actions/run-unit-tests
        with:
          build_env: ${{ env.BUILD_ENV }}
          tests: ${{ needs.repo-metadata-job.outputs.commit_message }}
      - id: unit-tests-comment
        name: Unit Test Comment
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: ${{ steps.run-unit-tests.outputs.tests_results_location }}/*.xml
          check_name: 'Unit Tests Report'
        if: (success() || failure()) && steps.run-unit-tests.outputs.tests_results_skip_report != 'true'
      - id: github-publish-unit-tests
        name: Github publish unit tests
        uses: ./.github/actions/publish-test-results
        with:
          build_id: ${{ env.BUILD_ID }}
          build_hash: ${{ env.BUILD_HASH }}
          test_type: unit
          pull_request: ${{ github.event.number }}
          tests_results_status: ${{ steps.run-unit-tests.outputs.tests_results_status }}
          tests_results_report_location: ${{ steps.run-unit-tests.outputs.tests_results_report_location }}
          cicd_github_token: ${{ secrets.CICD_GITHUB_TOKEN }}
        if: (success() || failure()) && steps.run-unit-tests.outputs.tests_results_skip_report != 'true'
      - id: publish-unit-tests
        name: Publish unit tests to Testmo
        uses: ./.github/actions/testmo-wrapper
        with:
          operation: submit
          github_sha: ${{ env.BUILD_HASH }}
          build_id: ${{ env.BUILD_ID }}
          testmo_token: ${{ secrets.TESTMO_TOKEN }}
          testmo_project_id: 1
          test_type: unit
          tests_results_location: ${{ steps.run-unit-tests.outputs.tests_results_location }}/*.xml
          debug: true
        if: (success() || failure()) && steps.run-unit-tests.outputs.tests_results_skip_report != 'true'
      - id: github-status
        name: Send Github Status
        uses: ./.github/actions/github-status
        with:
          test_type: unit
          test_results_status: ${{ steps.run-unit-tests.outputs.tests_results_status }}
          pull_request: ${{ github.event.number }}
          github_user: ${{ env.GITHUB_USER }}
          cicd_github_token: ${{ secrets.CICD_GITHUB_TOKEN }}
          tests_report_url: ${{ steps.github-publish-unit-tests.outputs.test_logs_url }}
        if: (success() || failure()) && steps.github-publish-unit-tests.outputs.tests_report_url != ''
  test-results-handler-job:
    name: Tests results handler
    runs-on: ubuntu-latest
    needs: [run-unit-tests-job]
    if: (success() || failure()) && (needs.run-unit-tests-job.outputs.tests_results_report_url != '')
    steps:
      - id: fetch-core
        name: Fetch Core Repo
        uses: actions/checkout@v3
      - id: tests-status-aggregator
        name: Tests status aggregator
        uses: ./.github/actions/tests-status-aggregator
        with:
          unit_tests_results_status: ${{ needs.run-unit-tests-job.outputs.tests_results_status }}
          unit_tests_results_report_url: ${{ needs.run-unit-tests-job.outputs.tests_results_report_url }}
          unit_tests_results_log_url: ${{ needs.run-unit-tests-job.outputs.tests_results_log_url }}
          testmo_unit_tests_results_report_url: ${{ needs.run-unit-tests-job.outputs.testmo_tests_results_report_url }}
      - id: tests-results-slack
        name: Tests results Slack notification
        if: steps.tests-status-aggregator.outputs.status != ''
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.CORE_SLACK_WEBHOOK }}
          SLACK_USERNAME: dotBot
          SLACK_ICON: https://avatars.slack-edge.com/2020-09-21/1362682893351_5b474f175640cf5f5912_72.png
          SLACK_COLOR: ${{ steps.tests-status-aggregator.outputs.color }}
          SLACK_TITLE: ${{ steps.tests-status-aggregator.outputs.status }}
          SLACK_MESSAGE: ${{ steps.tests-status-aggregator.outputs.message }}
          SLACK_FOOTER: ${{ env.PULL_REQUEST_URL }}
