name: core-tests
on:
  pull_request:
  push:
    branches:
      - master
      - release-*
jobs:
  module-matcher-job:
    name: Module Matcher
    runs-on: ubuntu-latest
    outputs:
      module_found: ${{ steps.module-matcher.outputs.module_found }}
    steps:
      - id: fetch-core
        name: Fetch Core repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: module-matcher
        name: Module Matcher
        uses: ./.github/actions/module-matcher
        with:
          current: core
  build-core-job:
    name: Build Core
    runs-on: ubuntu-latest
    env:
      DEBUG: true
    outputs:
      build-env: ${{ steps.read-cicd-local-env.outputs.build-env }}
      cache-metadata: ${{ steps.cache-core.outputs.cache-metadata }}
    steps:
      - id: fetch-core
        name: Fetch Core repo
        uses: actions/checkout@v3
      - id: read-cicd-local-env
        name: Read CICD local library
        run: |
          source ${GITHUB_WORKSPACE}/cicd/local-env.sh
        if: success()
      - id: build-core
        name: Build Core
        uses: ./.github/actions/build-core
        with:
          build-env: ${{ steps.read-cicd-local-env.outputs.build-env }}
        if: success()
      - id: core-cache-locator
        name: Core Cache Locator
        uses: ./.github/actions/core-cache-locator
        with:
          build-env: ${{ steps.read-cicd-local-env.outputs.build-env }}
          core-root: ${{ github.WORKSPACE }}
          cache-build-output: true
        if: success()
      - id: cache-core
        name: Cache Core
        uses: ./.github/actions/cache-core
        with:
          build-env: ${{ steps.read-cicd-local-env.outputs.build-env }}
          cache-locations: ${{ steps.core-cache-locator.outputs.cache-locations }}
        if: success()
  run-unit-tests-job:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build-core-job
    if: success()
    steps:
      - name: GITHUB CONTEXT
        run: echo "${{ toJson(github) }}"
        if: env.DEBUG == 'true'
      - id: fetch-core
        name: Fetch Core repo
        uses: actions/checkout@v3
      - id: restore-core
        name: Restore Core cache
        uses: ./.github/actions/restore-core
        with:
          cache-metadata: ${{ needs.build-core-job.outputs.cache-metadata }}
      - id: run-unit-tests
        name: Run Unit tests
        uses: ./.github/actions/run-unit-tests
        with:
          build-env: ${{ needs.build-core-job.outputs.build-env }}
