name: Build and Test

on:
  push:
    branches:
        - main
        - maven-test-*
  pull_request:
    branches:
        - main
        - maven-test-*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            core-web/node_modules
            core-web/installs
          key: ${{ runner.os }}-node-${{ hashFiles('core-web/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build and Test with Maven
        run: mvn --no-transfer-progress --install-after --fail-at-end  --show-version --update-snapshots verify --file pom.xml

      - name: Publish Test Results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test Results
          path: |
            **/target/surefire-reports/TEST-*.xml
            **/target/failsafe-reports/TEST-*.xml
            # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
