name: release-process-automation
on:
  release:
    types: [published]
jobs:
  release-process:
    name: Release Process Automation Test
    runs-on: ubuntu-18.04
    env:
      DOT_CICD_BRANCH: 19969-release-automation-pending-steps
      DOT_CICD_CLOUD_PROVIDER: github
      DOT_CICD_TARGET: core
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_USER: dotcmsbuild
      GITHUB_USER_TOKEN: ${{ secrets.USER_TOKEN }}
      PULL_REQUEST: ${{ github.event.number }}
      REPO_USERNAME: ${{ secrets.EE_REPO_USERNAME }}
      REPO_PASSWORD: ${{ secrets.EE_REPO_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SSH_RSA_KEY: ${{ secrets.EE_RSA_KEY }}
      DEBUG: true
    steps:
      - name: GITHUB CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"
        if: env.DEBUG == 'true'
      - name: Set Common Vars
        run: |
          BRANCH=$(basename "${{ github.ref }}")
          echo "BRANCH=${BRANCH}"
          IS_RELEASE='true'
          echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
          echo "EE_BRANCH=${BRANCH}" >> $GITHUB_ENV
          echo "BASE_FOLDER=$(pwd)" >> $GITHUB_ENV
          echo "IS_RELEASE=${IS_RELEASE}" >> $GITHUB_ENV
      - name: Prepare dot-cicd
        run: |
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/dotCMS/dot-cicd/${DOT_CICD_BRANCH}/seed/install-dot-cicd.sh)"
      - name: Build DotCMS Release Docker Image
        run: |
          dotcicd/library/pipeline.sh buildRelease
        if: env.IS_RELEASE != 'true'
      - name: Slack Notification
        if: success()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: dotcms-bot
          SLACK_MESSAGE: "This automated script is excited to announce the release of a new version of dotCMS - dotCMS v.xxxx"